version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: hr_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: hr_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_ALWAYS_EAGER=0
      - DJANGO_DEBUG=1
    depends_on:
      - redis

  celery:
    build: ./backend
    container_name: hr_celery
    command: celery -A hr_resume_ai worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_ALWAYS_EAGER=0
    depends_on:
      - backend
      - redis

  frontend:
    build: ./frontend
    container_name: hr_frontend
    ports:
      - "5501:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
